### ISSUE TITLE
How to catch errors thrown while logging in

### ISSUE THREAD

**Issue by jalenluorion** [qwazwsx/infinite-campus#15]
How do you catch an error thrown when login information is incorrect? I do not want the program to exit when an incorrect login error is thrown.

**Comment by qwazwsx** [comment]
This is a really good question! I should add an event so you can catch login errors with .on('error'). I'll look into this tomorrow... 

For now, you can use this as a workaround

```
var InfiniteCampus = require("infinite-campus")

try{
    const user = new InfiniteCampus('New York District', 'NY', 'JDoe12', 'XXXXXX')
} catch (err) {
    console.log("Error while logging in", err)
}
```

Read more about Try...Catch here
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

**Comment by jalenluorion** [comment]
Hey, thank you for responding so quickly :). Unfortunately, I have already used your workaround above before creating this issue, and the console prints `throw new Error(`[${prefix}][${errPrefix}] ${text}`)
    ^

Error: [LOGIN][F_BODY_0] Username/Password is incorrect.` before exiting. Isn't the point of a try-catch statement is to catch an error without causing the code to exit?

**Comment by qwazwsx** [comment]
Just pushed v3.1.2 which should fix this! It should be available on NPM in a few minutes. Just listen for the 'error' event and you can capture any errors thrown during the login process. If you don't listen to this event, the error will bubble up and kill the process. You can test it with this little script here:


```js
var InfiniteCampus = require("infinite-campus)

// deliberately incorrect credentials so it throws an error
const user = new InfiniteCampus('New York District', 'NY', 'JDoe12', 'XXXXXX')

// if you choose to listen to the error event, the process will keep running
// try to comment this out and notice how the process will exit
user.on('error', (err) => {
  console.log('We are handling the error: ', err)
})

// a little timer so we can observe the process either exiting (when 'error' isnt listened to) or continue to run (when there is an 'error' listener)
setInterval(() => {
  console.log('the process is still alive')
}, 500)


```
